# Generated by Django 5.1.4 on 2026-09-20 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website_url', models.URLField(blank=True, verbose_name='Site web')),
                ('terms_url', models.URLField(blank=True, verbose_name='Conditions générales')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil entreprise',
                'verbose_name_plural': 'Profil entreprise',
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_links', to='company.companyprofile')),
            ],
            options={
                'verbose_name': 'Lien utile',
                'verbose_name_plural': 'Liens utiles',
                'ordering': ['order', 'id'],
            },
        ),
    ]
