# Generated by Django 5.1.4 on 2026-09-20 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Code')),
                ('target_url', models.URLField(blank=True, verbose_name='URL cible')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lien réduit',
                'verbose_name_plural': 'Liens réduits',
            },
        ),
        migrations.CreateModel(
            name='OnlineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('schema', models.JSONField(blank=True, default=list, verbose_name='Champs')),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Interne'), ('confidential', 'Confidentiel'), ('restricted', 'Strictement confidentiel')], default='internal', max_length=20, verbose_name='Confidentialité')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert aux réponses')),
                ('success_message', models.CharField(default='Merci, votre réponse a bien été enregistrée.', max_length=255, verbose_name='Message de confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='projects.project')),
                ('short_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form', to='onlineforms.shortlink')),
            ],
            options={
                'verbose_name': 'Formulaire en ligne',
                'verbose_name_plural': 'Formulaires en ligne',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Réponses')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('respondent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='onlineforms.onlineform')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
