# Generated by Django 5.1.4 on 2026-09-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineform',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de réponse'),
        ),
    ]
