# Generated by Django 5.1.4 on 2026-09-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineforms", "0002_onlineform_deadline"),
        ("projects", "0005_project_clients_project_custom_field_defs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineform",
            name="diagrams",
            field=models.JSONField(blank=True, default=list, verbose_name="Diagrammes"),
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du modèle"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "schema",
                    models.JSONField(blank=True, default=list, verbose_name="Champs"),
                ),
                (
                    "diagrams",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Diagrammes"
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Interne"),
                            ("confidential", "Confidentiel"),
                            ("restricted", "Strictement confidentiel"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="Confidentialité par défaut",
                    ),
                ),
                (
                    "success_message",
                    models.CharField(
                        default="Merci, votre réponse a bien été enregistrée.",
                        max_length=255,
                        verbose_name="Message de confirmation",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Ouvert à tous"),
                            ("projects", "Projets spécifiques"),
                        ],
                        default="global",
                        max_length=20,
                        verbose_name="Portée",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="form_templates_scoped",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de formulaire",
                "verbose_name_plural": "Modèles de formulaire",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="onlineform",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forms",
                to="onlineforms.formtemplate",
            ),
        ),
    ]
