# Generated by Django 5.1.4 on 2026-09-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_alter_documenttemplate_doc_type"),
        ("onlineforms", "0003_onlineform_diagrams_formtemplate_onlineform_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="formtemplate",
            name="report_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Document Word ou PDF servant de rapport statistiques, dans lequel les diagrammes des questions s'insèrent comme variables.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_report_templates",
                to="documents.documenttemplate",
                verbose_name="Modèle de rapport (Word/PDF)",
            ),
        ),
        migrations.AddField(
            model_name="onlineform",
            name="report_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_reports",
                to="documents.documenttemplate",
                verbose_name="Modèle de rapport (Word/PDF)",
            ),
        ),
    ]
