# Generated by Django 5.1.4 on 2026-09-25 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineforms", "0005_formtemplate_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="forms/assets/", verbose_name="Fichier"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom d'origine"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="show_progress",
            field=models.BooleanField(
                default=True, verbose_name="Afficher la progression"
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="theme",
            field=models.JSONField(blank=True, default=dict, verbose_name="Apparence"),
        ),
        migrations.AddField(
            model_name="onlineform",
            name="show_progress",
            field=models.BooleanField(
                default=True, verbose_name="Afficher la progression"
            ),
        ),
        migrations.AddField(
            model_name="onlineform",
            name="theme",
            field=models.JSONField(blank=True, default=dict, verbose_name="Apparence"),
        ),
        migrations.CreateModel(
            name="FormUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Clé de la question"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="forms/uploads/", verbose_name="Fichier"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom d'origine"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="onlineforms.onlineform",
                    ),
                ),
            ],
        ),
    ]
