# Generated by Django 5.1.4 on 2026-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_client_project_client_projectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='styles',
            field=models.JSONField(blank=True, default=dict, verbose_name='Styles du projet'),
        ),
    ]
