# Generated by Django 5.1.4 on 2026-09-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documenttemplate_doc_type'),
        ('projects', '0004_project_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='projects_multi', to='projects.client', verbose_name='Clients associés'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_field_defs',
            field=models.JSONField(blank=True, default=list, help_text='[{key,label,type}] où type ∈ text/textarea/number/date/boolean/select', verbose_name='Définitions de champs personnalisés'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Valeurs des champs personnalisés'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.project', verbose_name='Projet parent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.client', verbose_name='Fiche client (principal)'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu / lien')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='meetings', to='documents.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('note', 'Note'), ('decision', 'Décision'), ('risk', 'Risque'), ('action', 'Action'), ('incident', 'Incident'), ('info', 'Information')], default='note', max_length=20, verbose_name='Catégorie')),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Interne'), ('confidential', 'Confidentiel'), ('restricted', 'Strictement confidentiel')], default='internal', max_length=20, verbose_name='Confidentialité')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Auteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='documents.documentversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='projects.project')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='projects.meeting')),
            ],
            options={
                'verbose_name': 'Entrée de journal',
                'verbose_name_plural': 'Journal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='ex. SharePoint, Instances, Stacks…', max_length=100, verbose_name='Catégorie')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Lien')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Commentaire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
            options={
                'verbose_name': 'Lien projet',
                'verbose_name_plural': 'Liens projet',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
