# Generated by Django 5.1.4 on 2026-09-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_clients_project_custom_field_defs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tracking",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{tasks:[], milestones:[], risks:[], snapshots:[]} pour les diagrammes de suivi (Gantt, avancement, risques…).",
                verbose_name="Données de suivi de projet",
            ),
        ),
    ]
