# Generated by Django 5.1.4 on 2026-09-25 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="body_html",
            field=models.TextField(blank=True, verbose_name="Contenu enrichi"),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal",
                to="projects.client",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="event",
            field=models.CharField(blank=True, max_length=40, verbose_name="Événement"),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_automatic",
            field=models.BooleanField(default=False, verbose_name="Automatique"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="cancelled",
            field=models.BooleanField(default=False, verbose_name="Annulée"),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="body",
            field=models.TextField(blank=True, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("decision", "Décision"),
                    ("risk", "Risque"),
                    ("action", "Action"),
                    ("incident", "Incident"),
                    ("info", "Information"),
                    ("event", "Événement"),
                ],
                default="note",
                max_length=20,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal",
                to="projects.project",
            ),
        ),
    ]
