# Generated by Django 5.1.4 on 2026-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_journalentry_body_html_journalentry_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clients/",
                verbose_name="Logo du client",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/",
                verbose_name="Logo du projet (facultatif)",
            ),
        ),
    ]
