# Generated by Django 5.1.4 on 2026-09-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_client_logo_project_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="instances",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{name, ip, domain, url}] — serveurs / instances du projet.",
                verbose_name="Instances / machines",
            ),
        ),
    ]
