# Generated by Django 5.1.4 on 2026-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_instances"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="repos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{id, parent, name, url, component, instance}] — arborescence des dépôts Git : composante du projet et instance associée.",
                verbose_name="Dépôts Git",
            ),
        ),
    ]
