# Generated by Django 5.1.4 on 2026-09-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_companyprofile_styles"),
        ("projects", "0005_project_clients_project_custom_field_defs_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Collaborateur",
                "verbose_name_plural": "Collaborateurs",
            },
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="color",
            field=models.CharField(
                default="#38BDF8", max_length=20, verbose_name="Couleur"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams",
                to="company.teammember",
                verbose_name="Collaborateurs",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subteams",
                to="company.team",
                verbose_name="Équipe parente",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams",
                to="projects.project",
                verbose_name="Projets gérés",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="related_teams",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_from",
                to="company.team",
                verbose_name="Équipes liées",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborators",
                to="company.companyprofile",
            ),
        ),
    ]
