# Generated by Django 5.1.4 on 2026-09-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_teammember_options_remove_teammember_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usefullink",
            name="category",
            field=models.CharField(
                blank=True, default="Autre", max_length=100, verbose_name="Catégorie"
            ),
        ),
        migrations.AlterField(
            model_name="usefullink",
            name="url",
            field=models.URLField(max_length=1000, verbose_name="URL"),
        ),
    ]
