# Generated by Django 5.0.6 on 2026-09-19 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du modèle')),
                ('kind', models.CharField(choices=[('pdf', 'PDF positionné'), ('excel', 'Excel générique'), ('word', "Word d'analyse")], max_length=16, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_generic', models.BooleanField(default=True, help_text="Réutilisable sur n'importe quel projet.", verbose_name='Modèle générique')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='templates/bg/', verbose_name="Fond (image, pour l'éditeur)")),
                ('background_pdf', models.FileField(blank=True, null=True, upload_to='templates/bg/', verbose_name='Fond (PDF, fusionné à la génération)')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Définition')),
                ('default_confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Interne'), ('confidential', 'Confidentiel'), ('secret', 'Secret')], default='internal', max_length=16, verbose_name='Confidentialité par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Interne'), ('confidential', 'Confidentiel'), ('secret', 'Secret')], default='internal', max_length=16, verbose_name='Confidentialité')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données & variables')),
                ('current_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier courant')),
                ('current_version', models.PositiveIntegerField(default=0, verbose_name='Version courante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project', verbose_name='Projet')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttemplate', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='N° de version')),
                ('file', models.FileField(upload_to='documents/versions/', verbose_name='Fichier')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('author_initials', models.CharField(blank=True, max_length=8, verbose_name='Initiales')),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de documents',
                'ordering': ['-number'],
                'unique_together': {('document', 'number')},
            },
        ),
    ]
