# Generated by Django 5.1.4 on 2026-09-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('contact_type', models.CharField(choices=[('client', 'Contact client'), ('internal', 'Contact interne')], default='client', max_length=20, verbose_name='Type')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Logo du projet/client')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_contact', models.ForeignKey(blank=True, limit_choices_to={'contact_type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_client_contact', to='projects.contact', verbose_name='Contact client')),
                ('internal_contact', models.ForeignKey(blank=True, limit_choices_to={'contact_type': 'internal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_internal_contact', to='projects.contact', verbose_name='Contact interne')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
