# Generated by Django 5.1.4 on 2026-09-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='is_block_based',
            field=models.BooleanField(default=False, help_text='Si activé, le document est rendu à partir des blocs définis dans le schéma (éditeur visuel).', verbose_name='Modèle par blocs'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='builder_key',
            field=models.CharField(help_text="Clé du générateur (ex: project_tracking, generic_table, analysis_report). 'custom' = rendu à partir des blocs.", max_length=100, verbose_name='Générateur'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='schema',
            field=models.JSONField(blank=True, default=list, help_text='Liste de blocs (modèle visuel) ou de variables (JSON).', verbose_name='Schéma / Blocs'),
        ),
    ]
