# Generated by Django 5.0.6 on 2026-09-19 23:57

import django.db.models.deletion
import onlineforms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(default=onlineforms.models._make_code, editable=False, max_length=12, unique=True, verbose_name='Code court')),
                ('schema', models.JSONField(blank=True, default=list, verbose_name='Champs')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert aux réponses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_forms', to='core.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Formulaire en ligne',
                'verbose_name_plural': 'Formulaires en ligne',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='onlineforms.onlineform')),
            ],
            options={
                'verbose_name': 'Réponse de formulaire',
                'verbose_name_plural': 'Réponses de formulaires',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
