# Generated by Django 5.1.4 on 2026-09-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du modèle')),
                ('doc_type', models.CharField(choices=[('pdf_tracking', 'PDF de suivi de projet'), ('excel', 'Fichier Excel générique'), ('word_analysis', "Fichier Word d'analyse")], max_length=30, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('variables_schema', models.JSONField(blank=True, default=list, verbose_name='Schéma des variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('doc_type', models.CharField(choices=[('pdf_tracking', 'PDF de suivi de projet'), ('excel', 'Fichier Excel générique'), ('word_analysis', "Fichier Word d'analyse")], max_length=30, verbose_name='Type de document')),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Interne'), ('confidential', 'Confidentiel'), ('secret', 'Secret')], default='internal', max_length=20, verbose_name='Niveau de confidentialité')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données / variables')),
                ('current_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier courant')),
                ('current_version', models.PositiveIntegerField(default=0, verbose_name='Version courante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire de modification')),
                ('author_initials', models.CharField(max_length=10, verbose_name="Initiales de l'auteur")),
                ('data_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Données à cette version')),
                ('file', models.FileField(blank=True, null=True, upload_to='versions/', verbose_name='Fichier de la version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de documents',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
