# Generated by Django 5.1.4 on 2026-09-20 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du modèle')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('docx', 'Word')], max_length=10, verbose_name='Type de fichier')),
                ('builder_key', models.CharField(help_text='Clé du générateur (ex: project_tracking, generic_table, analysis_report). Utilise le générateur générique si inconnu.', max_length=100, verbose_name='Générateur')),
                ('schema', models.JSONField(blank=True, default=list, help_text='Liste de définitions de variables au format JSON.', verbose_name='Schéma des variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_system', models.BooleanField(default=False, help_text='Modèle générique fourni par défaut (non supprimable côté UI).', verbose_name='Modèle système')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Interne'), ('confidential', 'Confidentiel'), ('restricted', 'Strictement confidentiel')], default='internal', max_length=20, verbose_name='Confidentialité')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Valeurs des variables')),
                ('current_version', models.PositiveIntegerField(default=0, verbose_name='Version courante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire de modification')),
                ('author_initials', models.CharField(max_length=10, verbose_name="Initiales de l'auteur")),
                ('author_name', models.CharField(blank=True, max_length=150, verbose_name="Nom de l'auteur")),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Interne'), ('confidential', 'Confidentiel'), ('restricted', 'Strictement confidentiel')], default='internal', max_length=20, verbose_name='Confidentialité')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Données figées')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier généré')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de document',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
