# Generated by Django 5.1.4 on 2026-09-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentasset_documenttemplate_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du document'),
        ),
    ]
