# Generated by Django 5.1.4 on 2026-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documenttemplate_projects_documenttemplate_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='doc_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('docx', 'Word'), ('pptx', 'PowerPoint')], max_length=10, verbose_name='Type de fichier'),
        ),
    ]
