# Generated by Django 5.1.4 on 2026-09-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_alter_documenttemplate_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("en", "English"),
                    ("de", "Deutsch"),
                    ("it", "Italiano"),
                ],
                default="fr",
                max_length=5,
                verbose_name="Langue",
            ),
        ),
    ]
