# Generated by Django 5.1.4 on 2026-09-25 16:07

from django.db import migrations, models


def backfill_languages(apps, schema_editor):
    """Initialise languages=[language] et names={language: name} sur l'existant."""
    Template = apps.get_model("documents", "DocumentTemplate")
    for tpl in Template.objects.all():
        lang = tpl.language or "fr"
        changed = False
        if not tpl.languages:
            tpl.languages = [lang]
            changed = True
        if not tpl.names:
            tpl.names = {lang: tpl.name}
            changed = True
        if changed:
            tpl.save(update_fields=["languages", "names"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_documenttemplate_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des codes de langue pris en charge par ce modèle (ex: ['fr', 'en', 'de']). Un modèle peut en proposer une ou plusieurs.",
                verbose_name="Langues disponibles",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="names",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Nom du modèle pour chaque langue, ex: {'fr': 'Offre d'emploi', 'en': 'Job offer'}.",
                verbose_name="Noms par langue",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("en", "English"),
                    ("de", "Deutsch"),
                    ("it", "Italiano"),
                ],
                default="fr",
                help_text="Langue par défaut du modèle (repli si une langue demandée n'est pas disponible).",
                max_length=5,
                verbose_name="Langue principale",
            ),
        ),
        migrations.RunPython(backfill_languages, noop),
    ]
