# Generated by Django 5.1.4 on 2026-09-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_seed_a3_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("xlsx", "Excel"),
                    ("docx", "Word"),
                    ("pptx", "PowerPoint"),
                    ("md", "Markdown"),
                    ("a3", "Template A3 (PNG / PDF)"),
                    ("brochure", "Brochure"),
                    ("lettre", "Lettre"),
                    ("mail", "Mail"),
                    ("offre", "Offre"),
                ],
                max_length=10,
                verbose_name="Type de fichier",
            ),
        ),
    ]
