# Generated by Django 5.1.4 on 2026-09-20 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Logo du client')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, help_text='Code / référence du projet (facultatif)', max_length=100, verbose_name='Référence interne')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('on_hold', 'En pause'), ('archived', 'Archivé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('client', 'Contact client'), ('internal', 'Contact interne')], max_length=10, verbose_name='Type')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='projects.project')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['kind', 'last_name'],
            },
        ),
    ]
