# Generated by Django 5.1.4 on 2026-09-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fields_schema', models.JSONField(blank=True, default=list, verbose_name='Champs du formulaire')),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Interne'), ('confidential', 'Confidentiel'), ('secret', 'Secret')], default='internal', max_length=20, verbose_name='Niveau de confidentialité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('short_code', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Code du lien réduit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='projects.project')),
            ],
            options={
                'verbose_name': 'Formulaire en ligne',
                'verbose_name_plural': 'Formulaires en ligne',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Réponses')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_app.onlineform')),
            ],
            options={
                'verbose_name': 'Réponse de formulaire',
                'verbose_name_plural': 'Réponses de formulaires',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
