# Generated by Django 5.1.4 on 2026-09-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenttemplate_is_block_based_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='template_assets/', verbose_name='Image')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image de modèle',
                'verbose_name_plural': 'Images de modèles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Page de garde, sommaire, page de suivi : {cover_title, cover_subtitle, include_cover, include_suivi, include_toc}.', verbose_name='Réglages de mise en page'),
        ),
    ]
