# Generated by Django 5.1.4 on 2026-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='styles',
            field=models.JSONField(blank=True, default=dict, verbose_name='Styles globaux'),
        ),
    ]
