# Generated by Django 5.1.4 on 2026-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_doc_date'),
        ('projects', '0004_project_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='templates_scoped', to='projects.project'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='scope',
            field=models.CharField(choices=[('global', 'Ouvert à tous'), ('projects', 'Projets spécifiques')], default='global', max_length=20, verbose_name='Portée'),
        ),
    ]
