# Generated by Django 5.1.4 on 2026-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='ui_prefs',
            field=models.JSONField(blank=True, default=dict, verbose_name="Préférences d'interface"),
        ),
    ]
