# Generated by Django 5.0.6 on 2026-09-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website_url', models.URLField(blank=True, verbose_name='Site web')),
                ('terms_url', models.URLField(blank=True, verbose_name='Conditions générales')),
                ('other_links', models.JSONField(blank=True, default=list, help_text='Liste d\'objets {"label": "...", "url": "..."}', verbose_name='Autres liens utiles')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Société émettrice',
                'verbose_name_plural': 'Société émettrice',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('client', 'Contact client'), ('internal', 'Contact interne')], max_length=16, verbose_name='Type')),
                ('first_name', models.CharField(max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('role', models.CharField(blank=True, max_length=128, verbose_name='Fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Logo client')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_contact', models.ForeignKey(blank=True, limit_choices_to={'kind': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_client', to='core.contact', verbose_name='Contact client')),
                ('internal_contact', models.ForeignKey(blank=True, limit_choices_to={'kind': 'internal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_internal', to='core.contact', verbose_name='Contact interne')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-updated_at'],
            },
        ),
    ]
